### ISSUE TITLE
Constructor name

### ISSUE THREAD

**Issue by rhalff** [npm/npmlog#10]
Not really a bug, but a bit confusing:

```
var log = exports = module.exports = new EE
```

It would be nice if the constructor name was something like NpmLog.

Missing methods are now blamed on EventEmitter.

```
var log = require('npmlog');
log.debug('test');
    ^
TypeError: Object #<EventEmitter> has no method 'debug'
    at Object.<anonymous> (/home/rhalff/git/fbpx-cli/test.js:3:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```

**Comment by helio-frota** [comment]
Hi, how to reproduce this ?

**Comment by rhalff** [comment]
Seems to not occur anymore:

test.js:
```js
const log = require('npmlog');
log.debug('test');
```

```js
/tmp/reproduce/test.js:3
log.debug('test');
    ^

TypeError: log.debug is not a function
    at Object.<anonymous> (/tmp/reproduce/test.js:3:5)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.runMain (module.js:607:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
```

It used to throw `TypeError: Object #<EventEmitter> has no method 'debug'`

Probably fixed by better error reporting from node itself.

Which means this issue can be closed.
