### ISSUE TITLE
Problem with npm and npmlog

### ISSUE THREAD

**Issue by lybertybox** [npm/npmlog#3]
Hello,i have install Node.js in my QNAP TS219P II, When i start npm, npm write this : 
module.js:340
    throw err;
          ^
Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at /share/HDA_DATA/.qpkg/nodejs/node/bin/npm:18:11
    at Object.<anonymous> (/share/HDA_DATA/.qpkg/nodejs/node/bin/npm:86:3)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

Can you help me to solve this problem Please
Thanx
Lyberty

**Comment by a598799539** [comment]
I type the following in mac terminal and work:
```shell
ln -s ../lib/node_modules/npm/bin/npm-cli.js npm
```

**Comment by liyunsheng** [comment]
made a soft link for npm work

**Comment by eshansingh** [comment]
Completely uninstall node (from EVERYWHERE, symlinks and everything) and reinstall. Worked for me.

**Comment by ZanderZhang** [comment]
I just download from http://nodejs.org/download/ and fixed.

**Comment by fsebbah** [comment]
I have the same problem today with the version 5.8.0 of node on Mac Yosemite.
Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:20:13
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:76:3)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)

I uninstall and reinstall node via brew.

**Comment by fsebbah** [comment]
I uninstall and delete the links and after I reinstall node and now it's ok.

**Comment by rakotomandimby** [comment]
Same as @a598799539 .
I got this error because I scp'd a currently untared version of node:
`scp -r node-v4.4.5-linux-x64 c7-abt-spray:/home/mrakotomandimby/`
This lead to transform the `npm` symlink to a real file.
When it is not a symlink anymore, this error occurs.
To solve this, 

- I tar'd the folder 
- scp it
- untar'd it

The symlink was preserved and no error anymore.

**Comment by helio-frota** [comment]
hi, this can be closed ?

**Comment by revelt** [comment]
Yeah, let's close this!
