### ISSUE TITLE
Throw error for updating npm

### ISSUE THREAD

**Issue by erinjerri** [npm/npmlog#37]
I was trying to install Salesforce's Lightning Design System and other component libraries, have had a ton of issues with Gulp and NPM/Node failing to install properly. More on my post [here](https://github.com/salesforce-ux/design-system/issues/225)

I received this error.

`npm install react-lightning-design-system
module.js:442
    throw err;
    ^

Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:20:13
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:76:3)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)`

**Comment by wkuckro** [comment]
similar issue, different app

**Comment by erinjerri** [comment]
Try updating to the latest version of node and try again.

**Comment by iarna** [comment]
The above error is because the global install of npm became corrupted somehow. With very old versions of npm this could happen sometimes when updating it. Regardless, as you say, the solution is to reinstall node.

(Failures to load a module aren't ever actually an issue with that module. Generally they should be reported to the requiring module, in this case, [npm](https://github.com/npm/npm) (support@npmjs.com).)
