### ISSUE TITLE
TypeError: log.gauge.isEnabled is not a function

### ISSUE THREAD

**Issue by avkonst** [npm/npmlog#61]
I have got the following package.json script definition:
```
{
    "scripts": {
        "build-css": "node-sass-chokidar --importer=node_modules/node-sass-tilde-importer src/ -o src/"
     }
}
```

When I run it, it produces the following crash:
```
[build-css] C:\Projects\Other\react-site\node_modules\npm\node_modules\npmlog\log.js:57
log.progressEnabled = log.gauge.isEnabled()
                                ^

TypeError: log.gauge.isEnabled is not a function
    at Object.<anonymous> (C:\Projects\Other\react-site\node_modules\npm\node_modules\npmlog\log.js:57:33)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at C:\Projects\Other\react-site\node_modules\npm\bin\npm-cli.js:19:13
    at Object.<anonymous> (C:\Projects\Other\react-site\node_modules\npm\bin\npm-cli.js:75:3)
```

I have commented out the line `log.progressEnabled = log.gauge.isEnabled()`, and it started working now.

**Comment by aliwatters** [comment]
Same error; on Ubuntu 18.04

```
ali@neptune:~$ uname -a
Linux neptune 4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

ali@neptune:~$ lsb_release -a 
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic

ali@neptune:~$ node -v
v10.10.0

ali@neptune:~$ which node
/usr/local/bin/node

ali@neptune:~$ dpkg -l nodejs
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name            Version      Architecture Description
+++-===============-============-============-====================================
ii  nodejs          8.10.0~dfsg- amd64        evented I/O for V8 javascript

ali@neptune:~$ npm -v
/usr/local/lib/node_modules/npm/node_modules/npmlog/log.js:57
log.progressEnabled = log.gauge.isEnabled()
                                ^

TypeError: log.gauge.isEnabled is not a function
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npmlog/log.js:
57:33)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:22:13
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:153:3)

ali@neptune:~$ sudo vi /usr/local/lib/node_modules/npm/node_modules/npmlog/log.js
[sudo] password for ali:
// commented out line 57

ali@neptune:~$ npm -v
6.4.1
```

Hope there are some clues there.

**Comment by SergeMathieu** [comment]
OS Windows 7
In my case, after installing version of Nodejs 8.12.0, I had the same error.
**log.gauge.isEnabled is not a function**
I could get rid of it in two steps:
1) delete the ../nodejs directory from my installation.
2) launch again the windows installer **node-v8.12.0-x64.msi**, during the workflow installation, I clicked on the button "Repair".
It solved the issue.

**Comment by syedaliuzair** [comment]
Thanks you so much Serge

> OS Windows 7
> In my case, after installing version of Nodejs 8.12.0, I had the same error.
> **log.gauge.isEnabled is not a function**
> I could get rid of it in two steps:
> 
> 1. delete the ../nodejs directory from my installation.
> 2. launch again the windows installer **node-v8.12.0-x64.msi**, during the workflow installation, I clicked on the button "Repair".
>    It solved the issue.

Thank you so much SergeMathieu. It helped me a lot . 
I have searched many links but never succeed.

**Comment by SergeMathieu** [comment]
You're welcome syedaliuzair.
It took me also a little bit of time to find this solution so, to help other people is a great pleasure ;)

**Comment by AdrianBinDC** [comment]
Any ideas how to resolve this on a Raspbian installation?
