### ISSUE TITLE
[BUG] v5.0.0 - Error: Cannot find module 'object-assign'

### ISSUE THREAD

**Issue by matz3** [npm/npmlog#81]
# What / Why

> When requiring v5.0.0 there is an error thrown 'Cannot find module 'object-assign''

## When

```js
require("npmlog");
```

## Where

* npm/npmlog

### Current Behavior

An error is thrown when the module is required.

```
Error: Cannot find module 'object-assign'
Require stack:
- ~/tmp/npmlog-issue/node_modules/gauge/theme-set.js
- ~/tmp/npmlog-issue/node_modules/gauge/themes.js
- ~/tmp/npmlog-issue/node_modules/gauge/index.js
- ~/tmp/npmlog-issue/node_modules/npmlog/log.js
- internal/preload
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (~/tmp/npmlog-issue/node_modules/gauge/theme-set.js:2:20)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '~/tmp/npmlog-issue/node_modules/gauge/theme-set.js',
    '~/tmp/npmlog-issue/node_modules/gauge/themes.js',
    '~/tmp/npmlog-issue/node_modules/gauge/index.js',
    '~/tmp/npmlog-issue/node_modules/npmlog/log.js',
    'internal/preload'
  ]
}
```

### Steps to Reproduce

* Node.js v14.15.5
* npm v6.14.11
* macOS 11.4

```shell
npm init --yes && npm i npmlog@5.0.0 && node -r npmlog
```

### Expected Behavior

* There shouldn't be an error when the module is required

## Who

* n/a

## References

* https://github.com/SAP/ui5-logger/pull/238

**Comment by wraithgar** [comment]
This is actually a bug in [gauge](https://github.com/npm/gauge). It uses `object-assign` but doesn't include it in its manifest.


https://github.com/npm/gauge/blob/master/theme-set.js#L2

**Comment by wraithgar** [comment]
`gauge@3.0.1` has a correct manifest now and thus should act properly inside npmlog
